name: intl_translation
version: 0.17.10+1
author: Dart Team <misc@dartlang.org>
description: >-
  Contains code to deal with internationalized/localized messages,
  date and number formatting and parsing, bi-directional text, and
  other internationalization issues.

homepage: https://github.com/dart-lang/intl_translation
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  analyzer:
  args:
  dart_style:
  intl:
  path:
  petitparser:
dev_dependencies:
  test:
